# This file was generated by GoReleaser. DO NOT EDIT.
cask "ec2ssh" do
  name "ec2ssh"
  desc "Simplify SSH connections to AWS EC2 instances"
  homepage "https://github.com/ivoronin/ec2ssh"
  version "2025.12.05"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ec2ssh"

  on_macos do
    on_intel do
      url "https://github.com/ivoronin/ec2ssh/releases/download/#{version}/ec2ssh_Darwin_x86_64.tar.gz"
      sha256 "8c1179df0801df797c629cb62e2d73d6fd9a8c35626f72be7e3c45db609bc9ad"
    end
    on_arm do
      url "https://github.com/ivoronin/ec2ssh/releases/download/#{version}/ec2ssh_Darwin_arm64.tar.gz"
      sha256 "4cd39a661de55737c1f49b515d910973eae6138a12241e95059865fa4755e45c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ivoronin/ec2ssh/releases/download/#{version}/ec2ssh_Linux_x86_64.tar.gz"
      sha256 "4cec36c7786f83c98bfbabbfb3320bb8c06be5b98024f9bb7ae82636caec71b6"
    end
    on_arm do
      url "https://github.com/ivoronin/ec2ssh/releases/download/#{version}/ec2ssh_Linux_arm64.tar.gz"
      sha256 "9fe301a5fade83f01c3eeff003739adb7d599ea0d9c662f0cc27e7ed844b45f5"
    end
  end

  postflight do
    ln -sf "#{HOMEBREW_PREFIX}/bin/ec2ssh" "#{HOMEBREW_PREFIX}/bin/ec2scp"
    ln -sf "#{HOMEBREW_PREFIX}/bin/ec2ssh" "#{HOMEBREW_PREFIX}/bin/ec2sftp"
    ln -sf "#{HOMEBREW_PREFIX}/bin/ec2ssh" "#{HOMEBREW_PREFIX}/bin/ec2list"
  end

  uninstall_postflight do
    rm -f "#{HOMEBREW_PREFIX}/bin/ec2scp"
    rm -f "#{HOMEBREW_PREFIX}/bin/ec2sftp"
    rm -f "#{HOMEBREW_PREFIX}/bin/ec2list"
  end

  # No zap stanza required
end
