# This file was generated by GoReleaser. DO NOT EDIT.
cask "ec2ssh" do
  name "ec2ssh"
  desc "Simplify SSH connections to AWS EC2 instances"
  homepage "https://github.com/ivoronin/ec2ssh"
  version "2025.12.05"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ec2ssh"

  on_macos do
    on_intel do
      url "https://github.com/ivoronin/ec2ssh/releases/download/#{version}/ec2ssh_Darwin_x86_64.tar.gz"
      sha256 "cfcba0fec54efb6149fff31025d9636b81db0afde4efee838bce5bff79dac2c5"
    end
    on_arm do
      url "https://github.com/ivoronin/ec2ssh/releases/download/#{version}/ec2ssh_Darwin_arm64.tar.gz"
      sha256 "a3a04b4e05695a3026770239ecadae7d49db20809a1fedecd60c0fa6cc6684d5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ivoronin/ec2ssh/releases/download/#{version}/ec2ssh_Linux_x86_64.tar.gz"
      sha256 "e1c07d0877ea81e9cd8be6813c5616a4507d14dada548b614e62295a72763c22"
    end
    on_arm do
      url "https://github.com/ivoronin/ec2ssh/releases/download/#{version}/ec2ssh_Linux_arm64.tar.gz"
      sha256 "11725358653ca3f1c0634def773680988ce403942b6d6a9be62a01302b142598"
    end
  end

  postflight do
    system_command "ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/ec2ssh", "#{HOMEBREW_PREFIX}/bin/ec2scp"]
    system_command "ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/ec2ssh", "#{HOMEBREW_PREFIX}/bin/ec2sftp"]
    system_command "ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/ec2ssh", "#{HOMEBREW_PREFIX}/bin/ec2list"]
  end

  uninstall_postflight do
    system_command "rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/ec2scp"]
    system_command "rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/ec2sftp"]
    system_command "rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/ec2list"]
  end

  # No zap stanza required
end
